model_path: "deepseek/deepseek-r1-distill-llama-70b:free"  # Using Hugging Face API
api_key: "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"  # ✅ Add your API key here

model_config: 
    max_new_tokens: 512
    temperature: 0.7
    context_length: 4096
