model_path: "deepseek/deepseek-r1-distill-llama-70b:free"  # Using Hugging Face API
api_key: "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"  # ✅ Add your API key here

model_config: 
    max_new_tokens: 512
    temperature: 0.7
    context_length: 4096
